let vDateBracke = date(addmonths('$(vToday)',-12),'DD/MM/YY');
set vContractorZenith = 'IBM_FIGO','DT','SOFTLYR_MD','IBM_SO';
set vContractorMpo = 'No','No';
set vContractorNAP = 'IBM_FIGO','SOFTLYR_MD','IBM_NCS';
set vLane = 'Intra Team','No';
set vGeo2Geo = 'APACAPAC','APACEMEA','EMEAEMEA','EMEAAPAC';
set vEorderShipment = '*IBM.VENDOR','*IBM.Canada','*Crossdock_CDN';
set vEorderOrder = '*IBM.VENDOR','*IBM.Canada','*Crossdock_CDN';