$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/0. Main.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Teams/0.1 Main Interpipes.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/1. Sale_Buy.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/0. Owners.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/4. HU_Items.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/7. FA.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/11. Specific_data_all_clients.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/12. Specific_data_all_clients_buy.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/14. DIMC.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/15. Sale_FirstBE.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/16. Buy_LastBE.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/26. sale_finance_service_tariff_items.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/34. Full BEs.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/60. DB Booking Details.qvs]);


$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/Team/3. Interpipes.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/1. missing_awb.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/2. dues no store.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/5. IOT.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/4. Amount.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/6. late_cw.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/7. timeliness_completeness.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/8. cw_timeliness_completeness.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/20. missing_hawb.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/21. missing_chawb.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/22. missing_tracking_number.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/32. not_booked.qvs]);

Brooker_report:
left keep(sale_service_specific_data)
LOAD
    "HBL / HAWB" as sale_hawb,
    ARRIBO,
    "CONFIRMACION ARRIBO",
    DECLARACION,
    "CANAL DE AFORO",
    "PAGO TAXES",
    "LIBERACION ADUANA",
    ENTREGA,
    OBSERVACIONES,
    [TIEMPO CONFIRMACION ARRIBO],
    [TIEMPO DECLARACION],
    [TIEMPO PAGO TAXES],
    [TIEMPO LIBERACION ADUANA],
    [TIEMPO ENTREGA],
    [Error CUSRES],
    [CUSRES Resolve Time]
    
FROM [lib://Geo_AMS/LogisticsAnalyst/LATAM/REPORTE MENSUAL IBM 2022.xlsx]
(ooxml, embedded labels, table is Hoja1);


idde:
left keep(hu_items)
LOAD

    INVOICE as sale_hu_invoice_number,
    "VENDOR CODE" as idde_vendor_code,
    "INVOICE STATUS" as idde_invoice_status,
    "SHIPMENT STATUS" as idde_shipment_status,
    NGEO as idde_ngeo,
    NDET as idde_ndet,
    SU as idde_su,
    NADO as idde_nado,
    NRET as idde_nret,
    1 as idde_flag,
    AMOUNT as idde_amount
    
FROM [lib://Geo_AMS/Automation/BI/Interpipes/LATAM/Invoice shipment created no tracking.xlsx]
(ooxml, embedded labels, table is Sheet1);




