buy_service_specific_data:
left keep(buy_basic)
LOAD
    buy_service_id,
    IBM_buy_requested_service as buy_requested_service,
    IBM_buy_adhoc_reference as buy_adhoc_reference,
    IBM_buy_chargeable_weight_kg as buy_chargeable_weight_kg,
    IBM_buy_service_order_scenario as buy_service_order_scenario,
    IBM_buy_HAWB as buy_hawb
    

FROM [lib://SCO-BI-Common Shared Data  Row/Geoflow_Buy_Service_IBM.qvd]
(qvd);


solidigm_buy_specific_info:
left keep(buy_basic)
LOAD
//     SOLIDIGM_buy_service_app_source,
//     SOLIDIGM_buy_service_record_date,
//     SOLIDIGM_buy_service_system_id,
    SOLIDIGM_buy_service_id as buy_service_id,
//     SOLIDIGM_buy_service_reference_1,
//     SOLIDIGM_buy_service_reference_2,
//     SOLIDIGM_buy_service_reference_3,
//     SOLIDIGM_buy_service_reference_4,
//     SOLIDIGM_buy_service_reference_5,
//     SOLIDIGM_buy_service_reference_6,
//     SOLIDIGM_buy_service_reference_7,
//     SOLIDIGM_buy_service_reference_8,
//     SOLIDIGM_buy_service_reference_9,
//     SOLIDIGM_buy_service_reference_10,
//     SOLIDIGM_buy_service_remarks,
//     SOLIDIGM_buy_service_remarks2,
    SOLIDIGM_buy_service_bill_of_lading_number as buy_bol,
    SOLIDIGM_buy_service_airwaybill_number as buy_hawb,
//     SOLIDIGM_buy_service_carrier1,
//     SOLIDIGM_buy_service_carrier2,
//     SOLIDIGM_buy_service_carrier3,
//     SOLIDIGM_buy_service_carrier4,
//     SOLIDIGM_buy_service_carrierConfirmedItems,
//    SOLIDIGM_buy_service_carrierConfirmedVolume,
//     SOLIDIGM_buy_service_eventUpdate,
//     SOLIDIGM_buy_service_flowType,
//     SOLIDIGM_buy_service_Flow,
//     SOLIDIGM_buy_service_itServices,
//     SOLIDIGM_buy_service_knCovidsurcharge,
//     SOLIDIGM_buy_service_knCustoms,
//     SOLIDIGM_buy_service_knEDICharge,
//     SOLIDIGM_buy_service_knEngineeringServices,
//     SOLIDIGM_buy_service_knEquipment,
//     SOLIDIGM_buy_service_knEuImportsystem,
//     SOLIDIGM_buy_service_knHScode,
//     SOLIDIGM_buy_service_knMiscBlueCollar,
//     SOLIDIGM_buy_service_knMiscManager,
//     SOLIDIGM_buy_service_knMiscWhiteCollar,
//     SOLIDIGM_buy_service_knSatBlueCollar,
//     SOLIDIGM_buy_service_knSatManager,
//     SOLIDIGM_buy_service_knSatWhiteCollar,
//     SOLIDIGM_buy_service_knSunBlueCollar,
//     SOLIDIGM_buy_service_knSunManager,
//     SOLIDIGM_buy_service_knSunWhiteCollar,
//     SOLIDIGM_buy_service_knWarehouseHandling,
//     SOLIDIGM_buy_service_nnrFtlLightPrice,
//     SOLIDIGM_buy_service_nnrIdmEnvelop,
//     SOLIDIGM_buy_service_nnrIdmEnvelopLogo,
//     SOLIDIGM_buy_service_nnrIdmFilesimport,
//     SOLIDIGM_buy_service_nnrIdmIajLabels,
//     SOLIDIGM_buy_service_nnrLightTruck,
//     SOLIDIGM_buy_service_nnrManagementFee
  SOLIDIGM_buy_service_carrierConfirmedWeight as carrierConfirmedWeight
FROM [lib://SCO-BI-Common Shared Data  Row/Geoflow_Buy_Service_SOLIDIGM.qvd]
(qvd);


concatenate(buy_service_specific_data)
load distinct 
    *
resident solidigm_buy_specific_info;

drop table solidigm_buy_specific_info;


[buy_number_HAWB]:
left join(buy_service_specific_data)
Load distinct
    buy_hawb,
    count(distinct buy_service_id) as buy_id_hawb_qty

resident [buy_service_specific_data] group by buy_hawb;