newcu_specific_info:
left keep(sale_basic)
LOAD

    sale_service_id,
    Sale_Service_NEWCUS_Tracking_Number as NEWCUS_Tracking_Number,
    Sale_Service_NEWCUS_House_Air_Way_Bill as NEWCUS_House_Air_Way_Bill,
    Sale_Service_NEWCUS_Carrier_Weight as NEWCUS_Carrier_Weight,
    Sale_Service_NEWCUS_House_Air_Way_Bill as NEWCUS_Customer_House_Airway_Bill
FROM [lib://SCO-BI-Common Shared Data  Row/Geoflow_Sale_Service_NEWCUS.qvd]
(qvd);


white_glove_mpo:
left keep(sale_basic)
LOAD
    //sale_service_systemid,
    sale_service_id,
    //WHITE_GLOVE_sale_service_reference_1,
    //WHITE_GLOVE_sale_service_reference_2,
    //WHITE_GLOVE_sale_service_reference_3,
    //WHITE_GLOVE_sale_service_reference_4,
    //WHITE_GLOVE_sale_service_reference_5,
    //WHITE_GLOVE_sale_service_reference_6,
    //WHITE_GLOVE_sale_service_reference_7,
    //WHITE_GLOVE_sale_service_reference_8,
    //WHITE_GLOVE_sale_service_reference_9,
    //WHITE_GLOVE_sale_service_reference_10,
    //WHITE_GLOVE_sale_service_bill_to_party_id,
    //WHITE_GLOVE_sale_service_bill_to_name,
    //WHITE_GLOVE_sale_service_bill_to_name2,
    //WHITE_GLOVE_sale_service_bill_to_address,
    //WHITE_GLOVE_sale_service_bill_to_address2,
    //WHITE_GLOVE_sale_service_bill_to_city,
    //WHITE_GLOVE_sale_service_bill_to_postal_code,
    //WHITE_GLOVE_sale_service_bill_to_region_state,
    //WHITE_GLOVE_sale_service_bill_to_country_code,
    WHITE_GLOVE_sale_service_businessUnit,
    WHITE_GLOVE_sale_service_remarks
    //WHITE_GLOVE_Sale_Service_app_source,
    //WHITE_GLOVE_Sale_Service_record_date
FROM [lib://SCO-BI-Common Shared Data  Row/Geoflow_Sale_Service_WHITE_GLOVE.qvd]
(qvd);


concatenate(newcu_specific_info)
LOAD
*
resident white_glove_mpo;

drop table white_glove_mpo;