
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Chervon/0.1 Main.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/0. Main.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/1. Sale_Buy.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/4. HU_Items.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/15. Sale_FirstBE.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/19. eorder_shipment.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/65. sale_last_be.qvs]);

$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/7. timeliness_completeness.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/31. net_on_time.qvs]);
$(Must_Include=[lib://Geo_AMS/Automation/BI/Plugins/Control Points/35. eorder_ack.qvs]);

cpm_temp:
left keep(sale_basic)
LOAD
    sale_service_id,
    cpm_kpi_tt,
    tt_flag
FROM [lib://Geo_AMS/Automation/BI/Plugins/Reports/cpm/cpm.csv]
(txt, utf8, embedded labels, delimiter is ',', msq);


left join(cpm_temp)
LOAD
    cso_number as sale_service_id,
    1 as cpm_net_flag
   
FROM [lib://Geo_AMS/LogisticsAnalyst/Plugins/SQTSCS/CP Netting.xlsx]
(ooxml, embedded labels, table is CPM);


cpm:
noconcatenate
load 
    sale_service_id,
    cpm_kpi_tt,
    tt_flag,
    if(cpm_net_flag = 1,1,0) as cpm_net_flag
resident cpm_temp;


drop table cpm_temp;